

# This file was *autogenerated* from the file finke-post.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)
from sage.all import *
from latties import *
import re,sys
from fractions import Fraction as Fr

# Обработка входной матрицы, всего 2 варианта:
# 1. [[1, 0], [0, 1]]
# 2. [1, 0]
#    [0, 1] 
rd=lambda t='',l='#':t if l==''or(re.search(r'\[\s*\[',t)and t.count('[')==t.count(']'))else rd(t+(x:=input())+'\n',x)
mat=lambda s=None,F=None:(E:=[[QQ(Fr(x))for x in re.findall(r'[-+]?\d+(?:/\d+|\.\d+)?',r)]for g in re.findall(r'\[[^][]*\]',s or(rd()if sys.stdin.isatty()else sys.stdin.read()))for r in g.split('\n')if re.search(r'\d',r)])and matrix(F or(QQ if any(e.denominator()>_sage_const_1  for r in E for e in r)else ZZ),E)

# Читаемый вывод матрицы
print_matrix=lambda A:print('\n'.join('[%s]'%', '.join(map(str,r))for r in A), "\n")

M = int(input())
B = mat().LLL()
F = B.T() * B
L, U = F.LU()
D = U.diagonal()

l = Lattice(D)

