

# This file was *autogenerated* from the file lattice.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from sage.all import *

class Lattice:
    def __init__(self, basis):
        self.basis = basis.change_ring(ZZ)
    
    def rank(self):
        return self.basis.rank()
    
    def gram_matrix(self):
        return self.basis.transpose() * self.basis

    def embedded_vec(self, coordinate_vec):
        coordinate_vec = vector(ZZ, coordinate_vec)
        return self.basis * coordinate_vec
    
    def bilinear_form(self, x, y):
        x = vector(ZZ, x)
        y = vector(ZZ, y)
        return x.transpose() * self.gram_matrix() * y
    
    def quadratic_form(self, x):
        return self.bilinear_form(x, x)
    
    def determinant(self):
        return self.gram_matrix.determinant()

L = Lattice(matrix(ZZ, [[_sage_const_1 , _sage_const_0 ], [_sage_const_1 , _sage_const_1 ]]))

print(L.determinant())

